<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-FAAJO8O" ignored="1" name="Test(failed)" tests="2" failures="2" timestamp="2022-07-31T16:30:35 IST" time="0.071" errors="0">
  <testcase name="test1" time="0.011" classname="RetryLogicDemo.TestCasesExample">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at RetryLogicDemo.TestCasesExample.test1(TestCasesExample.java:13)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.002" classname="RetryLogicDemo.TestCasesExample">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at RetryLogicDemo.TestCasesExample.test2(TestCasesExample.java:18)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="RetryLogicDemo.TestCasesExample">
    <ignored/>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test(failed) -->
